### ISSUE TITLE
Dataset Unavailable

### ISSUE THREAD

**Issue by koushiksrivats** [liuajian/Face-Anti-spoofing-Datasets#1]
Dear Authors,
Thank you for the great work.

I would like to make use of both the [CASIA-SURF](https://sites.google.com/qq.com/face-anti-spoofing/dataset-download/casia-surfcvpr2019) and [CASIA-SURF CeFA](https://sites.google.com/qq.com/face-anti-spoofing/dataset-download/casia-surf-cefacvpr2020) dataset.

However the links to download both these dataset currently seems to be not working.

Could you please help me with this and clarify if I could download the dataset from any alternate links ?

Thank You

**Comment by koushiksrivats** [comment]
The updated site can be found here:
[updated site](https://sites.google.com/view/face-anti-spoofing-challenge/welcome?authuser=0)

**Comment by Shan-Lee2k** [comment]
Hi, Did you have [CASIA-SURF](https://sites.google.com/qq.com/face-anti-spoofing/dataset-download/casia-surfcvpr2019) and [CASIA-SURF CeFA](https://sites.google.com/qq.com/face-anti-spoofing/dataset-download/casia-surf-cefacvpr2020) dataset?
And  you can share it with me?
